export const makesAndModels = [
    {
        make: "BMW",
        models: ["8 Series", "i8", "M5"],
    },
    {
        make: "Alpha Romeo",
        models: ["Giulia", "Stelvio", "4C Spider"],
    },
];

export const inventory = [
    {
        key: 10,
        make: "Audi",
        model: "TT RS",
        exteriorColor: "yellow",
        year: 2018,
        imageUrl: "https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        bodyStyle: "Coupe",
        msrp: 67600,
    },
    {
        key: 1,
        make: "Lamborghini",
        model: "Aventador LP700-4",
        exteriorColor: "orange",
        year: 2017,
        imageUrl: "https://images.pexels.com/photos/39501/lamborghini-brno-racing-car-automobiles-39501.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        bodyStyle: "Coupe",
        msrp: 399500,
    },
    {
        key: 2,
        make: "Lamborghini",
        model: "Huracan LP 640-4 EVO",
        exteriorColor: "green",
        year: 2020,
        imageUrl: "https://images.pexels.com/photos/2127733/pexels-photo-2127733.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        bodyStyle: "Coupe",
        msrp: 265951,
    },
    {
        key: 3,
        make: "Mazerati",
        model: "Gran Turismo Sport",
        exteriorColor: "black",
        year: 2019,
        imageUrl: "https://images.pexels.com/photos/977003/pexels-photo-977003.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        bodyStyle: "Convertible",
        msrp: 154590,
    },
    {
        key: 8,
        make: "BMW",
        model: "M4",
        exteriorColor: "white",
        year: 2020,
        imageUrl: "https://images.pexels.com/photos/794435/pexels-photo-794435.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        msrp: 78799,
    },
    {
        key: 9,
        make: "Audi",
        model: "A5",
        exteriorColor: "blue",
        year: 2019,
        imageUrl: "https://images.pexels.com/photos/244212/pexels-photo-244212.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        msrp: 52240,
    },
    {
        key: 4,
        make: "Alpha Romeo",
        model: "4C Spider",
        year: 2019,
        exteriorColor: "red",
        imageUrl: "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        msrp: 67150,
    },
    {
        key: 5,
        make: "Land Rover",
        model: "Range Rover",
        exteriorColor: "white",
        year: 2020,
        imageUrl: "https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        msrp: 90900,
    },
    {
        key: 6,
        make: "Mercedes-Benz",
        model: "GT R",
        exteriorColor: "gray",
        year: 2020,
        imageUrl: "https://images.pexels.com/photos/241316/pexels-photo-241316.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        msrp: 193940,
    },
    {
        key: 7,
        make: "Mercedes",
        model: "GT C",
        exteriorColor: "yellow",
        year: 2020,
        imageUrl: "https://images.pexels.com/photos/2365572/pexels-photo-2365572.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
        msrp: 150900,
        bodyStyle: "Coupe",
    },
];

export const bodyStyles = ["Convertible", "Coupe", "HatchBack", "Minivan", "Sedan", "SUV"];